# Generated by Django 3.2.8 on 2022-03-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0002_rename_designationd_esignation_designation_designation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_team',
            old_name='create_team_team_count',
            new_name='create_team_count',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_attendance_status',
        ),
        migrations.RemoveField(
            model_name='create_team',
            name='create_team_team_status',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_topic_status',
        ),
        migrations.RemoveField(
            model_name='trainer_task',
            name='trainer_task_task_status',
        ),
    ]
