# Generated by Django 3.2.8 on 2022-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0003_auto_20220329_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
