# Generated by Django 3.2.8 on 2022-03-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0004_alter_topic_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_task',
            name='trainer_task_status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
